### ISSUE TITLE
onSecureHardwareNotAvailable false positives with freeRASP 6.0.0

### ISSUE THREAD

**Issue by olexale** [talsec/Free-RASP-Flutter#77]
**Describe the bug**
We are getting many `onSecureHardwareNotAvailable` callbacks on Android with freeRASP 6.0.0 on devices that work fine with freeRASP 5.0.4. I assume they are false positives caused by some changes in the latest update.

**To Reproduce**
Upgrade to freeRASP 6, run the app.

**Expected behavior**
freeRASP doesn't trigger this event.

**Please complete the following information:**
 - Device: Samsung J5 pro (in fact, many other devices are affected too)
 - OS version: Android 9
 - Version of freeRASP: 6.0.0

**Comment by xprikryl2** [comment]
Hi @olexale,

We located one bug regarding this issue, but it only occurs on Android 12 and 13. For API 31 and above, we used [this new flag](https://developer.android.com/reference/android/content/pm/PackageManager#FEATURE_HARDWARE_KEYSTORE) that should indicate whether the device has a hardware keystore. The flag return value is not consistent with the [KeyInfo#getSecurityLevel()](https://developer.android.com/reference/android/security/keystore/KeyInfo#getSecurityLevel()) that we used before. We reverted this change, and the bug should be fixed. 

For API 30 and below, the functionality remains the same. We are still using the same method [KeyInfo#isInsideSecureHardware()](https://developer.android.com/reference/android/security/keystore/KeyInfo#isInsideSecureHardware()). I tried to look into the logs for any outliers, and my first assumption is that the device you mentioned does not have hardware-backed keystore. Unfortunately, I wasn't able to find any official list or documentation that would support this hypothesis, and we do not have this device available to test it. 


![image](https://github.com/talsec/Free-RASP-Flutter/assets/14791624/b6fb130a-78ff-42f3-bb9d-de807b571699)
We will continue with this investigation. If you have this issue on other devices (API 30 and below) and could provide us with a list of these devices, it would be very helpful.

Best regards,
Ondřej Přikryl

**Comment by msikyna** [comment]
Hello @olexale ,

a new version [v6.1.0](https://github.com/talsec/Free-RASP-Flutter/releases/tag/v6.1.0) with the fix of the issue. It is also released on pub.dev.

Kind regards,
Talsec team

**Comment by olexale** [comment]
Hello @msikyna, 

We will give it a try soon. I'll get back to you with the results.
Thank you!

Kind regards,
Oleksandr

**Comment by msikyna** [comment]
Hello @olexale ,
does the issue still persist? Our data implies that it has been fixed.

Kind regards,
Talsec team

**Comment by olexale** [comment]
Hello @msikyna,

Thanks for getting back! I don't see this error in recent logs, so I assume it is fixed.

Best regards,
Oleksandr
